// <auto-generated />
using System;
using Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.Migrations
{
    [DbContext(typeof(TravelContext))]
    partial class TravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Api.Entities.Travel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destiny")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Travel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f417b5c0-5d27-413e-a6af-36e5db077890"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 320, DateTimeKind.Local).AddTicks(195),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1011),
                            Destiny = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("fed72eff-29f9-4361-84a0-835cbac75662"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1380),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1392),
                            Destiny = "Natal"
                        },
                        new
                        {
                            Id = new Guid("646d4da0-e6ff-405d-8eb4-4a5beacf89fc"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1407),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1409),
                            Destiny = "Maceio"
                        },
                        new
                        {
                            Id = new Guid("7d430870-4c50-4975-a286-bf34d12e91c7"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1417),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1418),
                            Destiny = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("de9d286a-23b8-4bbc-9ee6-b3736a1f638d"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1426),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1427),
                            Destiny = "Florianopolis"
                        },
                        new
                        {
                            Id = new Guid("8cd16bf1-e31e-4125-a960-a7ab0b055415"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1435),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1436),
                            Destiny = "Milão"
                        },
                        new
                        {
                            Id = new Guid("bb74cc0e-017d-4ead-84ce-5565603ec085"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1444),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1445),
                            Destiny = "Roma"
                        },
                        new
                        {
                            Id = new Guid("dba4343a-c5b6-444c-a504-1f21a5db5dc7"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1452),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1454),
                            Destiny = "Turim"
                        },
                        new
                        {
                            Id = new Guid("2f8694d7-8f4d-455b-a78c-e4e249099169"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1461),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1463),
                            Destiny = "Cancum"
                        },
                        new
                        {
                            Id = new Guid("42c98e99-d212-4d15-a005-d924d90b7831"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1470),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1472),
                            Destiny = "Nova York"
                        },
                        new
                        {
                            Id = new Guid("9d315805-5a98-4bbd-808a-fe52deca0ca3"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1479),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1481),
                            Destiny = "Londres"
                        },
                        new
                        {
                            Id = new Guid("d109b4c1-e18e-4b1e-b535-11d06b65ca23"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1488),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1490),
                            Destiny = "Manchester"
                        },
                        new
                        {
                            Id = new Guid("39eb5302-2139-4be7-be42-66ec34b6bea8"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1497),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1499),
                            Destiny = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("3bf2c14b-44d3-4212-aaf3-bf8ff8cc15df"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1506),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1507),
                            Destiny = "Madrid"
                        },
                        new
                        {
                            Id = new Guid("ed83637d-75d7-47e7-abb5-9a010fd6eae6"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1515),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1516),
                            Destiny = "Valencia"
                        },
                        new
                        {
                            Id = new Guid("3d670312-4950-4f68-8c43-0246837f330a"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1524),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1525),
                            Destiny = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("25cc01c5-20d0-45a7-b76c-182c6fdad6d8"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1533),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1534),
                            Destiny = "Porto"
                        },
                        new
                        {
                            Id = new Guid("59122d88-e508-4340-9409-c8b2cea65c7e"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1542),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1543),
                            Destiny = "Lisboa"
                        },
                        new
                        {
                            Id = new Guid("1cefe41b-7433-4395-9c23-7bb8d44e3aff"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1551),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1552),
                            Destiny = "Munique"
                        },
                        new
                        {
                            Id = new Guid("4d69ee14-6e0f-4ad6-9c56-e63cfdd3b41c"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1560),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1561),
                            Destiny = "Berlim"
                        },
                        new
                        {
                            Id = new Guid("fc682837-233e-4f6f-ae9c-79bdb53f530b"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1569),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1570),
                            Destiny = "Hamburgo"
                        },
                        new
                        {
                            Id = new Guid("fa14e6d6-c0f8-4cc8-9a0b-fc468f75a5cd"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1577),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1579),
                            Destiny = "Boston"
                        },
                        new
                        {
                            Id = new Guid("224ee90c-027e-4533-8507-2e0b9cde0125"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1586),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1587),
                            Destiny = "Porto Alegre"
                        },
                        new
                        {
                            Id = new Guid("9f28b968-f19c-4f3c-9781-badea1739a2e"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1595),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1596),
                            Destiny = "Tokio"
                        },
                        new
                        {
                            Id = new Guid("d415069d-cefc-4cde-ad0c-9151127f37f0"),
                            Date = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1604),
                            DateRegister = new DateTime(2021, 7, 2, 15, 47, 35, 323, DateTimeKind.Local).AddTicks(1605),
                            Destiny = "Moscow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
